# Site settings
title: CIS531
baseurl: "cis531-s25"
url: "https://kmicinski.com/"
description: "CIS531 -- Compilers at Syracuse (Fall '25)"
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
